AWSTemplateFormatVersion: '2010-09-09'
Description: Template to create lambda function with writing permition to S3 bucket

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: s3-lambda-cortijo