AWSTemplateFormatVersion: '2010-09-09'
Description: Create a ECR to deploy tasks

Resources:

  #TODO
  ExecutionRole:
  TaskRole:
  log-grup:


  Taskdefinition:
    Properties:
      Family: "Taskdefinition"
      ExecutionRoleArn: !GetAtt ExecutionRole.Arn
      TaskRoleArn: !GetAtt TaskRole.Arn
      Type: AWS::ECS::TaskDefinition
      RequiresCompatibilities:
      - FARGATE
      ContainerDefinitions:
        - Name:  "AppName"
          Image: "scrapping"
          Cpu: 256
          EntryPoint:
            - "node"
            - "run.js"
          Memory: 512
          Essential: true
          Environment:
          - Name: 'INDEX_URL'
            Value: "index.cortijodemazas.com/index"
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: log-grup
              awslogs-region: 'eu-west-1'
              awslogs-stream-prefix: "scrapping"

Outputs:
  TaskdefinitionARN:
    Value: !GetAtt Taskdefinition.Arn
    Export:
      Name: taskdefinition
