AWSTemplateFormatVersion: '2010-09-09'
Description: Create a ECR to deploy tasks

Resources:
  ExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "ecs-tasks.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonECS_FullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      # Policies:
      #   - PolicyName: AccessECR
      #     PolicyDocument:
      #       Version: 2012-10-17
      #       Statement:
      #         - Effect: Allow
      #           Action:
      #             - ecr:BatchGetImage
      #             - ecr:GetAuthorizationToken
      #             - ecr:GetDownloadUrlForLayer
      #           Resource: '*'
  # TaskRole:
  #   Type: "AWS::IAM::Role"
  #   Properties:
  #     AssumeRolePolicyDocument:
  #       Version: "2012-10-17"
  #       Statement:
  #         -
  #           Effect: "Allow"
  #           Principal:
  #             Service:
  #               - "ecs-tasks.amazonaws.com"
  #           Action:
  #             - "sts:AssumeRole"
  #     Path: /
  #     ManagedPolicyArns:
  #       - arn:aws:iam::02004621356:role/ecs-ec2-task
  #     Policies:
  #       - PolicyName: AccessECR
  #         PolicyDocument:
  #           Version: 2012-10-17
  #           Statement:
  #             - Effect: Allow
  #               Action:
  #                 - ecr:BatchGetImage
  #                 - ecr:GetAuthorizationToken
  #                 - ecr:GetDownloadUrlForLayer
  #               Resource: '*'

  log:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: ecs/tasks
      RetentionInDays: 7

  Taskdefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: "Taskdefinition"
      ExecutionRoleArn: !GetAtt ExecutionRole.Arn
      TaskRoleArn: !GetAtt ExecutionRole.Arn
      RequiresCompatibilities:
      - FARGATE
      NetworkMode: "awsvpc"
      ContainerDefinitions:
        - Name:  "AppName"
          Image: "scrapping"
          Cpu: 256
          EntryPoint:
            - "node"
            - "run.js"
          Memory: 512
          Essential: true
          Environment:
          - Name: 'INDEX_URL'
            Value: "index.cortijodemazas.com/index"
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref log
              awslogs-region: 'eu-west-1'
              awslogs-stream-prefix: "scrapping"

Outputs:
  TaskdefinitionARN:
    Value: !GetAtt Taskdefinition.Arn
    Export:
      Name: taskdefinition
