AWSTemplateFormatVersion: '2010-09-09'
Description: Create a ECR to deploy tasks

Resources:
  ##### ECS Cluster ####
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: scrapping
      ClusterSettings:
      - Name: containerInsights
        Value: enabled

Outputs:
  ClusterARN:
    Value: !GetAtt Cluster.Arn
    Export:
      Name: ecs-cluster
