AWSTemplateFormatVersion: '2010-09-09'
Description: Create a ECR to deploy tasks

Resources:
  ExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: role_taskDefinition_execution_role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "ecs-tasks.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonECS_FullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      Policies:
        - PolicyName: AccessECR
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ecr:BatchGetImage
                  - ecr:GetAuthorizationToken
                  - ecr:GetDownloadUrlForLayer
                Resource: '*'
  # TaskRole:
  #   Type: "AWS::IAM::Role"
  #   Properties:
  #     AssumeRolePolicyDocument:
  #       Version: "2012-10-17"
  #       Statement:
  #         -
  #           Effect: "Allow"
  #           Principal:
  #             Service:
  #               - "ecs-tasks.amazonaws.com"
  #           Action:
  #             - "sts:AssumeRole"
  #     Path: /
  #     ManagedPolicyArns:
  #       - arn:aws:iam::02004621356:role/ecs-ec2-task
  #     Policies:
  #       - PolicyName: AccessECR
  #         PolicyDocument:
  #           Version: 2012-10-17
  #           Statement:
  #             - Effect: Allow
  #               Action:
  #                 - ecr:BatchGetImage
  #                 - ecr:GetAuthorizationToken
  #                 - ecr:GetDownloadUrlForLayer
  #               Resource: '*'

  log:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: ecs/tasks
      RetentionInDays: 7

  Taskdefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: "ScrappingTaskdefinition"
      ExecutionRoleArn: !GetAtt ExecutionRole.Arn
      TaskRoleArn: !GetAtt ExecutionRole.Arn
      RequiresCompatibilities:
      - FARGATE
      NetworkMode: "awsvpc"
      Cpu: 256
      Memory: 512
      ContainerDefinitions:
        - Name:  "Scrapping"
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/scrapping:v1
          Cpu: 256
          Memory: 512
          Essential: true
          Environment:
          - Name: 'DB_TABLE'
            Value: "sentencias"
          - Name: 'REGION'
            Value: !Sub ${AWS::Region}
          - Name: 'INDEX_URL'
            Value: "http://app.cortijodemazas.com"
          - Name: 'SCRAPPING_URL'
            Value: "http://scrapping.com"
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref log
              awslogs-region: 'eu-west-1'
              awslogs-stream-prefix: "scrapping"

Outputs:
  TaskdefinitionARN:
    Value: !Ref Taskdefinition
    Export:
      Name: taskdefinition
